#!/bin/bash
# A simple Azure storage example

export AZURE_STORAGE_ACCOUNT=gakguk
export AZURE_STORAGE_ACCESS_KEY=pb4ole+R5XjXyOU9hlOMISPeXBJFmgUg9Gdwqr461cQ6wDOCtiGQRUtZkvaQUlTSta7ydxJF6unyzUJnAbU1PQ==

export container_name=stock
export blob_name=futures.txt

echo "Uploading the file..."
rm -f /home/cem/portakal/futures*.txt
azure storage blob download  $container_name futures.txt .
azure storage blob download  $container_name futures_ice.txt .
azure storage blob download  $container_name futures_pair.txt .
rm -f /home/cem/portakal/futures.csv
sed -e '$a\' /home/cem/portakal/futures.txt > /home/cem/portakal/futures_aaa.txt
rm /home/cem/portakal/futures.txt 
cat /home/cem/portakal/futures_aaa.txt /home/cem/portakal/futures_ice.txt >> /home/cem/portakal/futures.csv
