#!/bin/bash
# A simple Azure storage example

export AZURE_STORAGE_ACCOUNT=gakguk
export AZURE_STORAGE_ACCESS_KEY=pb4ole+R5XjXyOU9hlOMISPeXBJFmgUg9Gdwqr461cQ6wDOCtiGQRUtZkvaQUlTSta7ydxJF6unyzUJnAbU1PQ==

export container_name=stock
export blob_name=futures.txt

echo "Uploading the file..."
rm -f futures*.txt
azure storage blob download  $container_name futures.txt .
azure storage blob download  $container_name futures_ice.txt .
azure storage blob download  $container_name futures_pair.txt .
rm -f futures.csv
sed -e '$a\' futures.txt > futures_aaa.txt
rm futures.txt 
cat futures.txt futures_ice.txt >> futures.csv
